--
INSERT INTO s_function VALUES ('TEST_SYSTEM', '98', '-1', '功能测试', null, null, '1', '-1');
INSERT INTO s_function VALUES ('WEBSOCKET', '1', '0', 'websocket', null, null, '1', 'TEST_SYSTEM');
INSERT INTO s_function VALUES ('WEBSOCKET_DEMO_1', '1', '1', '测试1-连接', '/test/websocket/demo_1.do', null, '1', 'WEBSOCKET');
INSERT INTO s_function VALUES ('WEBSOCKET_DEMO_2', '2', '1', '测试2-注解实现', '/test/websocket/demo_2.do', null, '1', 'WEBSOCKET');
